#!/bin/sh
#
# cloudsql          Run google cloudsql proxy
#
# chkconfig: 2345 90 60
# description: Runs an instance of the google cloudsql proxy locally to enable
#              connections to cloudSQL database instances

### BEGIN INIT INFO
# Provides: cloudsql
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $network $syslog
# Default-Start:  2345
# Default-Stop: 90
# Short-Description: run cloudsql proxy
# Description: Google Cloud SQL Proxy
### END INIT INFO

. /etc/rc.d/init.d/functions

prog=cloud_sql_proxy
lockfile=/var/lock/subsys/cloud_sql_proxy
SCRIPT=/opt/cloudsql/cloud_sql_proxy
RUNAS=root

APPHOME=/opt/cloudsql/cloud_sql_proxy
APPETC=/etc/cloudsql/
APPCONFIG=$APPETC/cloudsql.conf

# Load application config
. $APPCONFIG

OPTIONS="-instances=$INSTANCE_ID=tcp:$MYSQL_PORT -credential_file=$CREDENTIAL_FILE $ADDITIONAL_OPTIONS"

PIDFILE=/var/run/$prog.pid
LOGFILE=/var/log/cloudsql.log

start() {
    if [ $UID -ne 0 ] ; then
        echo "User has insufficient privilege."
        exit 4
    fi
    [ -x $SCRIPT ] || exit 5
    [ -f $APPCONFIG ] || exit 6
    echo -n $"Starting $prog: "
    daemon $SCRIPT $OPTIONS &>> $LOGFILE &
    retval=$?
    echo
    if [ $retval -eq 0 ]; then
      pidof $prog > $PIDFILE
      touch $lockfile
    fi
}

stop() {
    if [ $UID -ne 0 ] ; then
        echo "User has insufficient privilege."
        exit 4
    fi
    echo -n $"Stopping $prog: "
        if [ -n "`pidfileofproc $prog`" ]; then
                killproc $SCRIPT
                RETVAL=3
        else
                failure $"Stopping $prog"
        fi
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
